from __future__ import annotations

import unittest
from pathlib import Path
from unittest import mock

from osai_security.release import PRODUCT_VERSION


ROOT = Path(__file__).resolve().parents[1]


class UiArchitectureTests(unittest.TestCase):
    def test_top_level_navigation_matches_project_and_run_boundaries(self) -> None:
        html = (ROOT / "osai_security" / "static" / "index.html").read_text(encoding="utf-8")
        self.assertIn(f'/static/app.css?v={PRODUCT_VERSION}', html)
        self.assertIn(f'/static/app.js?v={PRODUCT_VERSION}', html)
        self.assertIn('data-view="projects"', html)
        self.assertIn('data-view="surface"', html)
        self.assertIn('data-view="reasoning"', html)
        self.assertIn('data-view="assess"', html)
        self.assertIn('data-view="tools"', html)
        self.assertIn('data-view="archive"', html)
        self.assertIn('data-view="motor"', html)
        self.assertIn('05&nbsp; Testing tools', html)
        self.assertIn('06&nbsp; Assessment results', html)
        self.assertIn('07&nbsp; Model lab', html)
        self.assertIn(f'/static/reasoning.js?v={PRODUCT_VERSION}', html)
        self.assertNotIn('Run archive</button>', html)
        self.assertNotIn('id="run-dialog"', html)
        self.assertNotIn('data-view="evidence"', html)
        self.assertNotIn('data-view="review"', html)
        self.assertIn('id="project-organization-dialog"', html)

    def test_release_identity_check_covers_reasoning_script_cache_version(self) -> None:
        from scripts import check_release_identity

        index_path = (ROOT / "osai_security" / "static" / "index.html").resolve()
        original_read_text = Path.read_text

        def stale_reasoning_version(path: Path, *args: object, **kwargs: object) -> str:
            content = original_read_text(path, *args, **kwargs)  # type: ignore[arg-type]
            if path.resolve() == index_path:
                content = content.replace(
                    f"reasoning.js?v={PRODUCT_VERSION}",
                    "reasoning.js?v=stale-regression-fixture",
                )
            return content

        with mock.patch.object(Path, "read_text", stale_reasoning_version):
            errors = check_release_identity.release_identity_errors()

        self.assertIn(
            "reasoning.js cache version does not match the authoritative product version",
            errors,
        )

    def test_project_portfolio_supports_scale_and_recoverable_archive(self) -> None:
        script = (ROOT / "osai_security" / "static" / "app.js").read_text(encoding="utf-8")
        styles = (ROOT / "osai_security" / "static" / "app.css").read_text(encoding="utf-8")
        self.assertIn("Find a project", script)
        self.assertIn("All clients", script)
        self.assertIn("Open findings", script)
        self.assertIn("Last 30 days", script)
        self.assertIn("Group by", script)
        self.assertIn("data-pin-project", script)
        self.assertIn("/organization", script)
        self.assertIn("/archive", script)
        self.assertIn("/restore", script)
        self.assertIn("Evidence remains available", script)
        self.assertIn(".project-portfolio-controls", styles)
        self.assertIn(".project-list-results", styles)

    def test_model_lab_is_installation_scoped_and_fully_connected(self) -> None:
        script = (ROOT / "osai_security" / "static" / "app.js").read_text(encoding="utf-8")
        server = (ROOT / "osai_security" / "http_app.py").read_text(encoding="utf-8")
        styles = (ROOT / "osai_security" / "static" / "app.css").read_text(encoding="utf-8")
        self.assertIn("function renderMotorLab", script)
        self.assertIn("function wireMotorLab", script)
        self.assertIn('if (view === "motor") return openMotorLab()', script)
        self.assertIn("Independent second review required", script)
        self.assertIn("Add an accepted non-benchmark trace", script)
        self.assertIn("Create a reproducible 8B experiment", script)
        self.assertIn("Run exact tokenizer audit", script)
        self.assertIn("/api/motor-lab/operator-traces", script)
        self.assertIn("/api/motor-lab/experiments", script)
        self.assertIn('["api", "motor-lab"]', server)
        self.assertIn("self.motor_lab.save_review", server)
        self.assertIn(".motor-review-card", styles)
        self.assertIn("Confirm primary correction", script)
        self.assertIn("Reject training record", script)
        self.assertIn("review-conflict", script)
        self.assertIn("A correct <code>vulnerable=false</code> example should be confirmed", script)
        self.assertIn(".motor-experiment-detail", styles)

    def test_testing_tools_are_connected_project_workspaces(self) -> None:
        script = (ROOT / "osai_security" / "static" / "app.js").read_text(encoding="utf-8")
        self.assertIn('data-tool-tab="${id}"', script)
        self.assertIn("Campaigns", script)
        self.assertIn("Request Replay", script)
        self.assertIn("Workflows", script)
        self.assertIn("Interaction Monitor", script)
        self.assertIn("/testing-tools", script)
        self.assertIn("/tool-runs", script)
        self.assertIn("/interactions", script)
        self.assertIn("Complete curl replay", script)
        self.assertIn("Evidence-backed finding contract example", script)
        self.assertIn("HTTP success without every assertion passing remains evidence, not a vulnerability.", script)
        self.assertIn("saved pack ${snapshot.version}", script)
        self.assertIn("update ${currentPack.version} available", script)
        self.assertIn("Remove whitespace for matching", script)

    def test_dense_workspaces_use_vertical_reading_flow(self) -> None:
        styles = (ROOT / "osai_security" / "static" / "app.css").read_text(encoding="utf-8")
        self.assertIn(".content-grid{display:grid;grid-template-columns:minmax(0,1fr)", styles)
        self.assertIn(".tool-layout{display:grid;grid-template-columns:minmax(0,1fr)", styles)
        self.assertIn(".tool-pack-grid{display:grid;grid-template-columns:minmax(0,1fr)", styles)
        self.assertIn(".tool-pack-actions{display:grid;grid-template-columns:minmax(0,1fr)", styles)
        self.assertIn(".run-findings{display:grid;grid-template-columns:minmax(0,1fr)", styles)
        self.assertIn(".run-plan-list{display:grid;grid-template-columns:minmax(0,1fr)", styles)
        self.assertIn(".inventory-items{display:grid;grid-template-columns:minmax(0,1fr)", styles)

    def test_new_assessment_and_archive_are_separate_workspaces(self) -> None:
        script = (ROOT / "osai_security" / "static" / "app.js").read_text(encoding="utf-8")
        new_assessment = script[script.index("function renderNewAssessment"):script.index("function renderRunArchive")]
        archive = script[script.index("function renderRunArchive"):script.index("function occurrenceMarkup")]
        self.assertIn("${assessmentPanel(project)}", new_assessment)
        self.assertNotIn("project.runs.map(runMarkup)", new_assessment)
        self.assertIn("project.runs.map(runMarkup)", archive)
        self.assertNotIn("${assessmentPanel(project)}", archive)

    def test_new_assessment_offers_guided_and_advanced_run_modes(self) -> None:
        script = (ROOT / "osai_security" / "static" / "app.js").read_text(encoding="utf-8")
        server = (ROOT / "osai_security" / "http_app.py").read_text(encoding="utf-8")
        styles = (ROOT / "osai_security" / "static" / "app.css").read_text(encoding="utf-8")
        self.assertIn("Guided Autonomous Assessment", script)
        self.assertIn("Advanced configured assessment", script)
        self.assertIn('data-assessment-mode="guided"', script)
        self.assertIn('data-assessment-mode="advanced"', script)
        self.assertIn('id="guided-plan-form"', script)
        self.assertIn('name="endpoint_url"', script)
        self.assertIn('name="authorized_boundary"', script)
        self.assertIn('name="prohibited_behavior"', script)
        self.assertIn("No target traffic is sent during validation or planning", script)
        self.assertIn("The operator-defined outcome remains the authoritative success criterion", script)
        self.assertIn("/guided-plans", script)
        self.assertIn("/guided-validation", script)
        self.assertIn("/guided-runs", script)
        self.assertIn("/api/guided-support", script)
        self.assertIn('parts[3] == "guided-plans"', server)
        self.assertIn('parts[3] == "guided-validation"', server)
        self.assertIn('parts[3] == "guided-runs"', server)
        self.assertIn("function advancedAssessmentPanel", script)
        self.assertIn("function guidedPlanMarkup", script)
        self.assertIn("Authorization boundary · what AdverScope may do", script)
        self.assertIn("Target security policy · what the AI must not do", script)
        self.assertIn("Apply editable starter", script)
        self.assertIn("Check setup and estimate requests", script)
        self.assertIn("Reviewed mandatory baseline", script)
        self.assertIn("Model-added tests", script)
        self.assertIn("Estimated request allocation", script)
        self.assertIn("Capabilities deferred to Advanced mode", script)
        self.assertIn("function guidedRecoveryFor", script)
        self.assertIn('text.includes("authorization confirmation")', script)
        self.assertNotIn('text.includes("authorization") || text.includes("maximum requests")', script)
        self.assertIn("guided.plan.selected", script)
        self.assertIn("guided.discovery.completed", script)
        self.assertIn(".run-mode-options", styles)
        self.assertIn(".guided-plan-card", styles)
        self.assertIn(".guided-boundary-grid", styles)
        self.assertIn(".guided-allocation", styles)
        self.assertIn(".guided-recovery", styles)

    def test_advanced_run_model_label_uses_active_runtime_configuration(self) -> None:
        script = (ROOT / "osai_security" / "static" / "app.js").read_text(encoding="utf-8")
        panel = script[script.index("function advancedAssessmentPanel"):script.index("function guidedPlanMarkup")]
        self.assertIn('state.health?.dependencies?.model?.configured_model', panel)
        self.assertIn('Configured roles · generator ${esc(activeModel)}', panel)
        self.assertNotIn("ASUS GX10", panel)

    def test_runtime_contract_and_secure_model_provider_controls_are_visible(self) -> None:
        html = (ROOT / "osai_security" / "static" / "index.html").read_text(encoding="utf-8")
        script = (ROOT / "osai_security" / "static" / "app.js").read_text(encoding="utf-8")
        server = (ROOT / "osai_security" / "http_app.py").read_text(encoding="utf-8")
        self.assertIn('id="model-provider-dialog"', html)
        self.assertIn('type="password"', html)
        self.assertIn("held in process memory only", html)
        self.assertIn('api("/api/runtime")', script)
        self.assertIn("Frontend and backend versions do not match", script)
        self.assertIn('api("/api/model-providers")', script)
        self.assertIn("Session keys remain in memory only", script)
        self.assertIn('name="selected_profile"', html)
        self.assertIn('name="role_planner"', html)
        self.assertIn('name="role_generator"', html)
        self.assertIn('name="role_evaluator"', html)
        self.assertIn('name="role_adjudicator"', html)
        self.assertIn("New named profile", html)
        self.assertIn("Professional role qualification", script)
        self.assertIn('/api/model-providers/profiles/', script)
        self.assertIn('/api/model-providers/roles', script)
        self.assertIn('/qualification', script)
        self.assertIn('https://api.openai.com/v1', script)
        self.assertIn('https://api.z.ai/api/paas/v4', script)
        stylesheet = (ROOT / "osai_security" / "static" / "app.css").read_text(encoding="utf-8")
        self.assertIn('validation-note.error', stylesheet)
        self.assertIn('.modal#model-provider-dialog', stylesheet)
        self.assertIn('overflow-x:hidden', stylesheet)
        self.assertIn('role="planner"', (ROOT / "osai_security" / "model_gateway.py").read_text(encoding="utf-8"))
        self.assertIn('role="evaluator"', (ROOT / "osai_security" / "model_gateway.py").read_text(encoding="utf-8"))
        self.assertIn('["api", "runtime"]', server)
        self.assertIn('["api", "model-providers"]', server)

    def test_recovery_workflow_is_visible_sensitive_and_integrity_checked(self) -> None:
        html = (ROOT / "osai_security" / "static" / "index.html").read_text(encoding="utf-8")
        script = (ROOT / "osai_security" / "static" / "app.js").read_text(encoding="utf-8")
        server = (ROOT / "osai_security" / "http_app.py").read_text(encoding="utf-8")
        recovery = (ROOT / "osai_security" / "recovery.py").read_text(encoding="utf-8")
        self.assertIn('id="data-recovery-dialog"', html)
        self.assertIn('id="recovery-sensitive-ack"', html)
        self.assertIn("Include browser login sessions", html)
        self.assertIn("Stop AdverScope before replacement restore", html)
        self.assertIn("/api/project-transfers?acknowledge_sensitive=1", script)
        self.assertIn("/api/local-backup?acknowledge_sensitive=1", script)
        self.assertIn("professional_project_transfer", server)
        self.assertIn("_upload_project_transfer", server)
        self.assertIn("archive integrity verification failed", recovery)
        self.assertIn("restore-in-progress.json", recovery)
        self.assertIn("recover_interrupted_restore(config)", server)

    def test_project_navigation_refreshes_server_state_before_rendering(self) -> None:
        script = (ROOT / "osai_security" / "static" / "app.js").read_text(encoding="utf-8")
        navigate = script[script.index("async function navigate"):script.index("function wireRunButtons")]
        self.assertIn("return openProject(state.current.id, view)", navigate)
        self.assertNotIn("return renderProject(state.current, view)", navigate)

    def test_adaptive_turn_selector_uses_the_approved_guardrail_limit(self) -> None:
        script = (ROOT / "osai_security" / "static" / "app.js").read_text(encoding="utf-8")
        boundary = script[script.index("function updateRunBoundary"):script.index("async function downloadReport")]
        self.assertIn("guardrail?.max_turns_per_objective", boundary)
        self.assertIn("Array.from({length: maximumTurns}", boundary)
        self.assertIn("Up to ${turns} turns per objective", boundary)
        self.assertIn("const requestedTurns", boundary)
        self.assertIn("target?.capabilities?.memory || target?.capabilities?.transcript_replay", boundary)
        self.assertIn("adaptive conversation disabled until continuity transport is configured", boundary)
        self.assertIn("Math.min(requestedTurns, maximumTurns)", boundary)
        self.assertNotIn('adaptive.value = "1"', boundary)
        self.assertIn('configuredProfile.disabled = Boolean(target && !primaryIsGet)', boundary)
        self.assertIn('reconProfile.value = "attack-surface"', boundary)
        self.assertIn("const reconAvailable", boundary)
        self.assertIn("target?.runtime_readiness", boundary)
        self.assertIn("runtime preflight blocked", boundary)
        self.assertIn('runButton.dataset.projectReady !== "true"', boundary)

    def test_attack_surface_requires_an_explicit_conversation_transport(self) -> None:
        script = (ROOT / "osai_security" / "static" / "app.js").read_text(encoding="utf-8")
        self.assertIn('["memory","Target-managed conversation session"]', script)
        self.assertIn('["transcript_replay","Client-side transcript replay"]', script)
        self.assertIn('id="conversation-config-form"', script)
        self.assertIn("Map structured request history", script)
        self.assertIn("/conversation-config", script)
        self.assertIn("target?.conversation_config?.enabled", script)
        self.assertIn('["LLM01-SPLIT", "LLM01-CRESCENDO"]', script)

    def test_attack_surface_exposes_retained_connection_readiness(self) -> None:
        script = (ROOT / "osai_security" / "static" / "app.js").read_text(encoding="utf-8")
        styles = (ROOT / "osai_security" / "static" / "app.css").read_text(encoding="utf-8")
        server = (ROOT / "osai_security" / "http_app.py").read_text(encoding="utf-8")
        database = (ROOT / "osai_security" / "db.py").read_text(encoding="utf-8")
        self.assertIn('data-test-connection="${esc(target.id)}"', script)
        self.assertIn("function targetPreflightMarkup", script)
        self.assertIn("Exact retained request", script)
        self.assertIn("Exact retained response", script)
        self.assertIn("No message was submitted", script)
        self.assertIn("data-preflight-section", script)
        self.assertIn("async function testTargetConnection", script)
        self.assertIn("/preflights", script)
        self.assertIn('parts[5] == "preflights"', server)
        self.assertIn("target_preflight_runs", database)
        self.assertIn(".target-preflight", styles)

    def test_browser_targets_can_use_evaluator_only_response_proof_rules(self) -> None:
        script = (ROOT / "osai_security" / "static" / "app.js").read_text(encoding="utf-8")
        self.assertIn('const evaluationTargetSelect = $("evaluation-config-form").elements.target_id', script)
        self.assertIn('.filter((target) => target.kind === "browser-chatbot")', script)
        self.assertIn('evaluationTargetSelect.insertAdjacentHTML(', script)
        self.assertIn("expected_sha256", script)
        self.assertIn("finding_evidence", script)

    def test_assessment_navigation_waits_for_readiness_mutations(self) -> None:
        script = (ROOT / "osai_security" / "static" / "app.js").read_text(encoding="utf-8")
        self.assertIn("pendingProjectMutations: new Set()", script)
        self.assertIn("function trackProjectMutation", script)
        self.assertIn("async function waitForProjectMutations", script)
        self.assertIn("await waitForProjectMutations()", script)
        self.assertIn("trackProjectMutation(submitEvaluationConfig(event))", script)
        self.assertIn("trackProjectMutation(submitCapabilities(event))", script)
        self.assertIn("trackProjectMutation(submitGuardrail(event))", script)

    def test_attack_surface_prevents_silent_scope_approval_and_allows_unused_target_cleanup(self) -> None:
        script = (ROOT / "osai_security" / "static" / "app.js").read_text(encoding="utf-8")
        database = (ROOT / "osai_security" / "db.py").read_text(encoding="utf-8")
        server = (ROOT / "osai_security" / "http_app.py").read_text(encoding="utf-8")
        self.assertIn("Origin only, without a route, query, fragment, or credentials.", script)
        self.assertIn("Verify a target-owned visible outcome after each attempt", script)
        self.assertIn('name="outcome_stop_after_match"', script)
        self.assertIn('name="outcome_verification_timeout_ms"', script)
        self.assertIn("Proof propagation window", script)
        self.assertIn("browserOutcome.finding_evidence", script)
        self.assertIn("contractReady || targetProofReady", script)
        self.assertIn('name="blocked_prompt_patterns"', script)
        self.assertIn("Machine-enforced before target traffic", script)
        self.assertIn('"effect_constraints"', script)
        self.assertIn('"protected_object_patterns"', script)
        self.assertIn('"allowed_effect_patterns"', script)
        self.assertIn('"prohibited_effect_patterns"', script)
        self.assertIn("effect constraints are machine-enforced before traffic", script)
        self.assertIn('name="navigation_transport"', script)
        self.assertIn("HTTP/1.1 compatibility", script)
        self.assertIn("browser_profile?.navigation_transport", script)
        self.assertIn("data-browser-transport", script)
        self.assertIn("/browser-transport", script)
        self.assertIn("data-target-origin-form", script)
        self.assertIn("/origin", script)
        self.assertIn("Historical run snapshots are immutable", script)
        self.assertIn("data-target-transport-form", script)
        self.assertIn("Save pacing and recovery", script)
        self.assertIn("/transport-reliability", script)
        self.assertIn("Pacing applies even when automatic retries are disabled", script)
        self.assertIn('const deterministicProof = form.elements.proof_mode.value !== "model-review"', script)
        self.assertIn("proof_rule_ids: deterministicProof ?", script)
        self.assertIn('$("target-form").addEventListener("submit", submitTarget)', script)
        self.assertIn('"persistent_session", "full_page", "outcome_enabled", "outcome_case_sensitive"', script)
        self.assertIn('payload[name] = Boolean(form.elements[name]?.checked)', script)
        self.assertIn("visible proof · ${browserOutcome.id}", script)
        self.assertIn("data-delete-target", script)
        self.assertIn("async function deleteTarget", script)
        self.assertIn('status="draft"', database)
        self.assertIn("Explicit operator review and approval are required", database)
        self.assertIn('parts[3] == "targets" and method == "DELETE"', server)
        self.assertIn('"outcome_rule": {', server)

    def test_attack_surface_keeps_optional_inputs_but_moves_active_recon_to_runs(self) -> None:
        script = (ROOT / "osai_security" / "static" / "app.js").read_text(encoding="utf-8")
        surface = script.index("${targetSetupProfilePanel(project)}${scopePanel(project)}${targetPanel(project)}${guardrailPanel(project)}${artifactPanel(project)}${technicalInputsPanel(project)}")
        self.assertGreaterEqual(surface, 0)
        self.assertIn("02 · Attack surface", script)
        self.assertIn("03 · Execution guardrails", script)
        self.assertIn("04 · Optional technical inputs", script)
        self.assertNotIn('id="active-recon-form"', script)
        self.assertIn('name="recon_mode"', script)
        self.assertIn("Run-scoped reconnaissance", script)

    def test_native_llm03_artifacts_are_configured_and_reviewed_in_the_gui(self) -> None:
        script = (ROOT / "osai_security" / "static" / "app.js").read_text(encoding="utf-8")
        self.assertIn("function artifactPanel", script)
        self.assertIn("Model and supply-chain artifacts", script)
        self.assertIn("/artifact-profile", script)
        self.assertIn("native-artifact-static-analysis", script)
        self.assertIn('evaluation.evaluator === "deterministic-native-artifact-scanner"', script)
        self.assertIn("Artifact snapshot reference", script)
        self.assertIn("Exact native static-analysis report", script)
        self.assertIn("never imports packages, loads models, extracts archives, or executes artifact content", script)
        self.assertIn("Only explicitly linked objectives can be satisfied by this deterministic policy case", script)
        self.assertIn("No model judgment awards this objective", script)
        self.assertIn("Assessment validation telemetry", script)
        self.assertIn("intentionally sent no target request", script)
        self.assertIn("Current run evidence:", script)
        artifact_gate = script.index('technique.required_configuration === "artifact_adapter"')
        generic_chat_gate = script.index('technique.module_id && (target.kind === "api"')
        self.assertLess(artifact_gate, generic_chat_gate, "native non-chat adapters must be evaluated before the generic API chatbot exclusion")

    def test_each_selected_run_has_scoped_assess_evidence_and_review(self) -> None:
        script = (ROOT / "osai_security" / "static" / "app.js").read_text(encoding="utf-8")
        self.assertIn('data-run-tab="assess"', script)
        self.assertIn('data-run-tab="evidence"', script)
        self.assertIn('data-run-tab="review"', script)
        self.assertIn("occurrence.run_id === run.id", script)
        self.assertIn("validation.run_id === run.id", script)
        self.assertIn("filtered by the selected run ID at the data layer", script)
        self.assertIn("Approved boundary stop", script)

    def test_run_review_includes_contract_findings_and_expandable_exact_evidence(self) -> None:
        script = (ROOT / "osai_security" / "static" / "app.js").read_text(encoding="utf-8")
        self.assertIn("function runContractFindingMarkup", script)
        self.assertIn("EXACT CONTRACT EVIDENCE", script)
        self.assertIn("Contract validation telemetry", script)
        self.assertIn("contractRun.security_findings", script)
        self.assertIn('data-copy-tool-command', script)
        self.assertIn("function combinedRunCounts", script)
        self.assertIn("toolRun.assessment_run_id === run.id", script)

    def test_contract_objective_links_are_configurable_and_visible_as_deterministic_proof(self) -> None:
        script = (ROOT / "osai_security" / "static" / "app.js").read_text(encoding="utf-8")
        self.assertIn("Available objective IDs for deterministic contract proof", script)
        self.assertIn('"objective_ids":["obj_..."]', script)
        self.assertIn("Only objectives selected for a run can be satisfied", script)
        self.assertIn('result.proof_source === "deterministic-target-contract"', script)
        self.assertIn("Explicit objective-to-outcome link plus target-owned assertions", script)
        self.assertIn("Linked objective proof", script)
        self.assertIn("achieved · reproduced", script)

    def test_run_review_surfaces_exact_stored_web_carrier_separately_from_trigger_and_response(self) -> None:
        script = (ROOT / "osai_security" / "static" / "app.js").read_text(encoding="utf-8")
        self.assertIn("function storedCarrierEvidenceMarkup", script)
        self.assertIn('validationCase.adapter !== "stored-web-native"', script)
        self.assertIn("STORED CARRIER CONTENT USED BY THIS OBSERVATION", script)
        self.assertIn("This is the complete operator-attested carrier content retained for the test, not only the emitted marker.", script)
        self.assertIn("Exact content stored in the ${esc(carrierKind)}", script)
        self.assertIn("validationCase.prepared_content", script)
        self.assertIn("Carrier preparation record", script)
        self.assertIn("storedCarrierEvidenceMarkup(evaluation)", script)
        self.assertIn('const vulnerable = occurrence.case_status === "vulnerable" || evaluation.vulnerable === true', script)
        self.assertIn("function storedWebFindingStoryMarkup", script)
        self.assertIn("Finding evidence at a glance", script)
        self.assertIn("Injected review/document", script)
        self.assertIn("Vulnerable chatbot response", script)
        self.assertIn("Independent reproduction", script)
        self.assertIn("Captured ${esc(formatTimestamp(asset.created_at))}", script)
        self.assertIn('asset.kind === "carrier-screenshot"', script)
        self.assertIn('asset.kind === "response-screenshot"', script)
        review = script[script.index("function runReviewMarkup"):script.index("function renderProjectContext")]
        self.assertLess(review.index("${reviewWorkspace}"), review.index("${runValidationQualityMarkup(run)}"))

    def test_validation_telemetry_is_visible_and_exportable(self) -> None:
        script = (ROOT / "osai_security" / "static" / "app.js").read_text(encoding="utf-8")
        styles = (ROOT / "osai_security" / "static" / "app.css").read_text(encoding="utf-8")
        self.assertIn("Failure-analysis pipeline", script)
        self.assertIn("Cross-run validation quality", script)
        self.assertIn("data-adjudication-form", script)
        self.assertIn("/adjudications", script)
        self.assertIn("/telemetry", script)
        self.assertIn("Export telemetry JSON", script)
        self.assertIn("Attempt / finding reproduction", script)
        self.assertIn("confirmed_finding_reproducibility_rate", script)
        self.assertIn(".pipeline-flow", styles)

    def test_evidence_assurance_network_capture_and_cancellation_are_visible(self) -> None:
        script = (ROOT / "osai_security" / "static" / "app.js").read_text(encoding="utf-8")
        styles = (ROOT / "osai_security" / "static" / "app.css").read_text(encoding="utf-8")
        self.assertIn("function evidenceAssuranceMarkup", script)
        self.assertIn("candidate only · not a finding", script)
        self.assertIn("target-configured evidence contract", script)
        self.assertIn("function browserNetworkMarkup", script)
        self.assertIn("ACTUAL BROWSER NETWORK", script)
        self.assertIn("data-network-event", script)
        self.assertIn("function installExecutionControls", script)
        self.assertIn('/cancel`, {method:"POST"', script)
        self.assertIn("Cancellation requested", script)
        self.assertIn(".evidence-assurance", styles)
        self.assertIn(".browser-exchange", styles)
        self.assertIn(".run-head-actions", styles)

    def test_objectives_and_owasp_selection_are_explicit_and_run_scoped(self) -> None:
        script = (ROOT / "osai_security" / "static" / "app.js").read_text(encoding="utf-8")
        styles = (ROOT / "osai_security" / "static" / "app.css").read_text(encoding="utf-8")
        attack_surface = script[script.index("function renderAttackSurface"):script.index("function renderNewAssessment")]
        archive = script[script.index("function renderRunArchive"):script.index("function occurrenceMarkup")]
        self.assertIn("05 · Assessment objectives", script)
        self.assertIn("Attack goal", script)
        self.assertIn("False-positive exclusions", script)
        self.assertNotIn("owaspCoveragePanel(project", attack_surface)
        self.assertIn("owaspCoveragePanel(project, {archiveScoped:true})", archive)
        self.assertIn("All-run OWASP coverage", script)
        self.assertIn('name="run_objective"', script)
        objective_panel = script[script.index("function objectivePanel"):script.index("function coverageRecordMarkup")]
        self.assertNotIn('taxonomyPickerMarkup("objective")', objective_panel)
        self.assertIn("Objectives define attack intent and success. They do not silently select OWASP coverage.", script)
        self.assertIn("Complete catalog · stop after reproduced proof", script)
        self.assertIn("Versioned technique manifest", script)
        self.assertIn("Adaptive technique manifest", script)
        self.assertIn("it is not legacy execution", script)
        self.assertIn("plan.taxonomy_version && !plan.legacy_selection", script)
        self.assertIn("Target evidence contracts only", script)
        self.assertIn('name="execution_mode"', script)
        self.assertIn('name="${esc(prefix)}_risk"', script)
        self.assertIn('name="${esc(prefix)}_technique"', script)
        self.assertIn("run.assessment_plan", script)
        self.assertIn("not automated by this target adapter", script)
        self.assertNotIn('input[name="module"]:checked', script)
        self.assertIn(".taxonomy-picker", styles)
        self.assertIn(".coverage-grid", styles)
        self.assertIn(".archive-coverage", styles)
        self.assertIn("function coverageRecordMarkup", script)
        self.assertIn('class="coverage-technique"', script)
        self.assertIn("Exact chatbot response", script)
        self.assertIn('class="run-observation', script)

    def test_conditional_owasp_automation_is_target_scoped_and_transparent(self) -> None:
        script = (ROOT / "osai_security" / "static" / "app.js").read_text(encoding="utf-8")
        self.assertIn('id="evaluation-config-form"', script)
        self.assertIn("deterministic-agency-verifier", (ROOT / "osai_security" / "evaluation_profiles.py").read_text(encoding="utf-8"))
        self.assertIn("deterministic-misinformation-oracle", (ROOT / "osai_security" / "evaluation_profiles.py").read_text(encoding="utf-8"))
        self.assertIn("Conditionally automated", script)
        self.assertIn("techniqueReadyForTarget", script)
        self.assertIn("expected values stay evaluator-only", script.lower())
        self.assertIn("view evidence", script)

    def test_first_class_tool_agent_configuration_and_protocol_evidence_are_visible(self) -> None:
        script = (ROOT / "osai_security" / "static" / "app.js").read_text(encoding="utf-8")
        styles = (ROOT / "osai_security" / "static" / "app.css").read_text(encoding="utf-8")
        self.assertIn('name="tool_agent_enabled"', script)
        self.assertIn('name="tool_agent_profile"', script)
        self.assertIn("openai-chat-completions-tools", script)
        self.assertIn("Protected identity headers must use env:VARIABLE_NAME", script)
        self.assertIn("it never dispatches target tools", script.lower())
        self.assertIn('required_configuration === "tool_agent_adapter"', script)
        self.assertIn("function protocolEventMarkup", script)
        self.assertIn("function protocolTraceMarkup", script)
        self.assertIn("Normalized protocol and component trace", script)
        self.assertIn("Complete run AI protocol trace", script)
        self.assertIn("testCase.protocol_events", script)
        self.assertIn(".protocol-trace", styles)

    def test_native_rag_legacy_mcp_and_remaining_owasp_contract_controls_are_visible(self) -> None:
        script = (ROOT / "osai_security" / "static" / "app.js").read_text(encoding="utf-8")
        taxonomy = (ROOT / "osai_security" / "owasp.py").read_text(encoding="utf-8")
        self.assertIn('name="mcp_profile"', script)
        self.assertIn("legacy HTTP+SSE", script)
        self.assertIn("action_assertions", script)
        self.assertIn("LLM06-MCP-DEPUTY", script)
        self.assertIn("LLM08-MCP-BOUNDARY", script)
        self.assertIn("LLM01-MCP-CONTENT", script)
        self.assertIn("LLM03-MCP-INVENTORY", script)
        self.assertIn("inventory_sha256", script)
        self.assertIn("order-independent complete inventory digest", script)
        self.assertIn("Malicious metadata visibility is retained as an observation", script)
        self.assertIn("content injection becomes a finding only after", script.lower())
        self.assertIn('name="rag_profile"', script)
        self.assertIn("clean baseline", script)
        self.assertIn("authorized positive control", script)
        self.assertIn("queries again to verify marker absence", script)
        self.assertIn('"cleanup_verify_attempts":3', script)
        self.assertIn('"component":"knowledge-store"', script)
        self.assertIn('id="assessment-contract-recipe"', script)
        self.assertIn('id="load-assessment-contract-recipe"', script)
        self.assertIn('name="assessment_contract_recipe_reviewed"', script)
        self.assertIn('role <code>precondition</code>', script)
        self.assertIn('role <code>evidence</code>', script)
        self.assertIn("Replace unresolved recipe values before saving", script)
        self.assertIn("Security outcomes are reproduced automatically", script)
        for capability in ("artifact_inventory", "training_pipeline", "model_evaluation", "resource_telemetry"):
            self.assertIn(capability, script)
        for technique_id in ("LLM01-MULTIMODAL", "LLM03-MODEL", "LLM03-DEPS", "LLM04-DATA", "LLM04-BACKDOOR", "LLM10-TOKEN", "LLM10-COST"):
            self.assertIn(technique_id, taxonomy)

    def test_automated_pack_target_values_are_owned_by_attack_surface(self) -> None:
        script = (ROOT / "osai_security" / "static" / "app.js").read_text(encoding="utf-8")
        packs = (ROOT / "osai_security" / "tool_packs.py").read_text(encoding="utf-8")
        self.assertIn('id="technique-adapter-form"', script)
        self.assertIn("All target-specific routes, field names, identifiers, selectors, confirmation signals", script)
        self.assertIn("Add configured pack to project", script)
        self.assertIn("needs Attack Surface configuration", packs)
        self.assertIn('"confirmation_policy": "minimum-proof"', packs)
        for lab_assumption in ('"/api/score"', '"/api/datasets"', '"/chat/{level}"', '"/model/{model_id}/chat"', '"alpha"', '"beta"', '"gamma"'):
            self.assertNotIn(lab_assumption, packs)
        self.assertNotIn('value="/tokenize"', script)
        self.assertNotIn('value="/context-info"', script)

    def test_professional_layout_preserves_readability_at_common_widths(self) -> None:
        styles = (ROOT / "osai_security" / "static" / "app.css").read_text(encoding="utf-8")
        self.assertIn("Professional readability and responsive workspace density", styles)
        self.assertIn("@media (max-width: 1440px)", styles)
        self.assertIn(".context-rail { display: none; }", styles)
        self.assertIn("scrollbar-gutter: stable", styles)
        self.assertIn("font-size: 10px", styles)
        self.assertIn("min-height: 112px", styles)
        self.assertIn("overflow-x: auto", styles)


if __name__ == "__main__":
    unittest.main()
